apiVersion: apps/v1
kind: Deployment
metadata:
  name: jasmin
  namespace: jasmin
  labels:
    name: jasmin
    k8s.kuboard.cn/name: jasmin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jasmin
  template:
    metadata:
      labels:
        name: jasmin
    spec:
      containers:
        - name: jasmin
          image: jookies/jasmin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2775
              name: smpp-port
            - containerPort: 1401
              name: http-port
            - containerPort: 8990
              name: cli-port
          command: ["jasmind.py", "--enable-interceptor-client", "-u", "jcliadmin", "-p", "jclipwd"]
          lifecycle:
            postStart:
              exec:
                command: [ "sh", "-c", "cp /tmp/config/* /etc/jasmin/" ]
          volumeMounts:
            - name: jasmin-config
              mountPath: /tmp/config
            - name: jasmin-data
              mountPath: /etc/jasmin/store
            - name: jasmin-logs
              mountPath: /var/log/jasmin
        - name: interceptord-sidecar
          image: jookies/jasmin:latest
          imagePullPolicy: IfNotPresent
          command: ["interceptord.py"]
          lifecycle:
            postStart:
              exec:
                command: [ "sh", "-c", "cp /tmp/config/* /etc/jasmin/" ]
          volumeMounts:
            - name: interceptor-config
              mountPath: /tmp/config
        - name: dlrlookupd-sidecar
          image: jookies/jasmin:latest
          imagePullPolicy: IfNotPresent
          command: ["dlrlookupd.py"]
          lifecycle:
            postStart:
              exec:
                command: [ "sh", "-c", "cp /tmp/config/* /etc/jasmin/" ]
          volumeMounts:
            - name: dlrlookupd-config
              mountPath: /tmp/config
        - name: dlrd-sidecar
          image: jookies/jasmin:latest
          imagePullPolicy: IfNotPresent
          command: ["dlrd.py"]
          lifecycle:
            postStart:
              exec:
                command: [ "sh", "-c", "cp /tmp/config/* /etc/jasmin/" ]
          volumeMounts:
            - name: dlr-config
              mountPath: /tmp/config
        - name: deliversmd-sidecar
          image: jookies/jasmin:latest
          imagePullPolicy: IfNotPresent
          command: ["deliversmd.py"]
          lifecycle:
            postStart:
              exec:
                command: [ "sh", "-c", "cp /tmp/config/* /etc/jasmin/" ]
          volumeMounts:
            - name: deliversmd-config
              mountPath: /tmp/config
      volumes:
        - name: jasmin-config
          configMap:
            name: etc-jasmin
        - name: jasmin-data
          hostPath:
            path: /opt/jasmin/store
            type: DirectoryOrCreate
        - name: interceptor-config
          configMap:
            name: etc-interceptor
        - name: dlrlookupd-config
          configMap:
            name: etc-dlrlookupd
        - name: dlr-config
          configMap:
            name: etc-dlr
        - name: deliversmd-config
          configMap:
            name: etc-deliversmd
        - name: jasmin-logs
          hostPath:
            path: /opt/jasmin/logs
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: jasmin
    k8s.kuboard.cn/name: jasmin
  name: jasmin-cli
  namespace: jasmin
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: cli
      nodePort: 30990
      port: 8990
      protocol: TCP
      targetPort: cli-port
  selector:
    name: jasmin
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: jasmin
    k8s.kuboard.cn/name: jasmin
  name: jasmin-smpp-api
  namespace: jasmin
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: smpp
      nodePort: 30775
      port: 2775
      protocol: TCP
      targetPort: smpp-port
  selector:
    name: jasmin
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: jasmin
    k8s.kuboard.cn/name: jasmin
  name: jasmin-http-api
  namespace: jasmin
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      nodePort: 30401
      port: 1401
      protocol: TCP
      targetPort: http-port
  selector:
    name: jasmin
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-jasmin
  namespace: jasmin
data:
  jasmin.cfg: |
      # This is a simplified config version taken from the /etc/jasmin/jasmin.cfg file
      # Some parameters are slightly fine tuned for better performance, amqp and redis
      # parameters are updated accordingly to kubernetes requirements.
      [smpp-server]
      # Disabled to allow smpp stress tests without charging & billing management
      billing_feature    = False

      [sm-listener]
      publish_submit_sm_resp = False
      submit_max_age_smppc_not_ready = 30

      [deliversm-thrower]
      http_timeout = 10
      retry_delay = 90
      max_retries = 2

      [amqp-broker]
      host = rabbitmq-broker

      [redis-client]
      host = redis-server
      poolsize = 30

      [jcli]
      bind = 0.0.0.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-interceptor
  namespace: jasmin
data:
  interceptor.cfg: |
      # This is a simplified config version taken from the /etc/jasmin/interceptor.cfg file
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-dlrlookupd
  namespace: jasmin
data:
  dlrlookupd.cfg: |
      # This is the Jasmin DLR Lookup Daemon configuration file.
      # Some parameters are slightly fine tuned for better performance, amqp and redis
      # parameters are updated accordingly to kubernetes requirements.
      [dlr]
      dlr_lookup_retry_delay = 180
      dlr_lookup_max_retries = 1

      [amqp-broker]
      host = rabbitmq-broker

      [redis-client]
      host = redis-server
      poolsize = 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-dlr
  namespace: jasmin
data:
  dlr.cfg: |
      # This is the Jasmin DLR Lookup Daemon configuration file.
      # Some parameters are slightly fine tuned for better performance, amqp and redis
      # parameters are updated accordingly to kubernetes requirements.
      [dlr-thrower]
      http_timeout = 10
      retry_delay = 90
      max_retries = 1

      [amqp-broker]
      host = rabbitmq-broker

      [redis-client]
      host = redis-server
      poolsize = 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-deliversmd
  namespace: jasmin
data:
  deliversmd.cfg: |
      # This is the Jasmin Deliver-Sm Daemon configuration file.
      # Some parameters are slightly fine tuned for better performance, amqp and redis
      # parameters are updated accordingly to kubernetes requirements.
      [deliversm-thrower]
      http_timeout = 10
      retry_delay = 90
      max_retries = 1

      [amqp-broker]
      host = rabbitmq-broker

      [redis-client]
      host = redis-server
      poolsize = 30
