apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: jasmin
  labels:
    name: grafana
    k8s.kuboard.cn/name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 0
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          volumeMounts:
            - name: provisioning-ds-prometheus
              mountPath: /etc/grafana/provisioning/datasources
            - name: provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards-jasmin
              mountPath: /opt/grafana-dashboards/Jasmin
            - name: dashboards-rabbitmq
              mountPath: /opt/grafana-dashboards/RabbitMQ
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: provisioning-ds-prometheus
          configMap:
            name: provisioning-ds-prometheus
        - name: provisioning-dashboards
          configMap:
            name: provisioning-dashboards
        - name: dashboards-jasmin
          configMap:
            name: grafana-dashboards-jasmin
            optional: true
        - name: dashboards-rabbitmq
          configMap:
            name: grafana-dashboards-rabbitmq
            optional: true
        - name: grafana-data
          hostPath:
            path: /opt/grafana
            type: DirectoryOrCreate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: provisioning-ds-prometheus
  namespace: jasmin
data:
  prometheus.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: jasmin-prometheus-ds
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        basicAuth: false
        editable: false
        enabled: true
        version: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: provisioning-dashboards
  namespace: jasmin
data:
  dashboards.yml: |
    apiVersion: 1

    providers:
      - name: 'Jasmin'
        orgId: 1
        #folder: ''
        #folderUid: ''
        disableDeletion: false
        updateIntervalSeconds: 120
        allowUiUpdates: true
        options:
          path: /opt/grafana-dashboards
          foldersFromFilesStructure: true
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: grafana
    k8s.kuboard.cn/name: grafana
  name: grafana
  namespace: jasmin
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: grafana
      nodePort: 30300
      port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    name: grafana
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: jasmin
  labels:
    name: prometheus
    k8s.kuboard.cn/name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      initContainers:
        - name: file-ownership-fix
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c"]
          args:
            - chown 65534:65534 /prometheus
          volumeMounts:
            - name: dataprom
              mountPath: "/prometheus"
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
          ports:
            - containerPort: 9090
              name: prometheus-port
              protocol: TCP
          volumeMounts:
            - name: etcprom
              mountPath: /etc/prometheus
            - name: dataprom
              mountPath: /prometheus
      volumes:
        - name: etcprom
          configMap:
            name: promconf
        - name: dataprom
          hostPath:
            path: /opt/prometheus
            type: DirectoryOrCreate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promconf
  namespace: jasmin
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: jasmin
        static_configs:
          - targets:
              - 'jasmin-http-api:1401'
      - job_name: rabbitmq
        static_configs:
          - targets:
              - 'rabbitmq-broker:15692'
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: prometheus
    k8s.kuboard.cn/name: prometheus
  name: prometheus
  namespace: jasmin
spec:
  clusterIP: None
  clusterIPs:
    - None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    name: prometheus
  sessionAffinity: None
  type: ClusterIP
