apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  namespace: jasmin
  labels:
    name: rabbit
    k8s.kuboard.cn/name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbit
  template:
    metadata:
      labels:
        name: rabbit
    spec:
      hostname: rabbit
      containers:
      - name: rabbit
        image: rabbitmq:3.10-management-alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: etcrabbit
            mountPath: /etc/rabbitmq/conf.d
      volumes:
        - name: etcrabbit
          configMap:
            name: rabbit-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbit-conf
  namespace: jasmin
data:
  10-main.conf: |
    loopback_users.guest = false
    prometheus.return_per_object_metrics = true
    log.console = true
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: rabbit
    k8s.kuboard.cn/name: rabbit
  name: rabbitmq-broker
  namespace: jasmin
spec:
  clusterIP: None
  clusterIPs:
    - None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    name: rabbit
  sessionAffinity: None
  type: ClusterIP
