apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: jasmin
  labels:
    name: redis
    k8s.kuboard.cn/name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      hostname: redis
      containers:
      - name: redis
        image: redis:6-alpine
        imagePullPolicy: IfNotPresent
        command:
          - redis-server
          - "/etc/redis/redis.conf"
        env:
        - name: MASTER
          value: "true"
        volumeMounts:
        - mountPath: /etc/redis/
          name: redisconfig
      volumes:
        - name: redisconfig
          configMap:
            name: etcredis
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: redis
    k8s.kuboard.cn/name: redis
  name: redis-server
  namespace: jasmin
spec:
  clusterIP: None
  clusterIPs:
    - None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    name: redis
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcredis
  namespace: jasmin
data:
  redis.conf: ""
