apiVersion: apps/v1
kind: Deployment
metadata:
  name: smppsim
  namespace: jasmin
  labels:
    name: smppsim
    k8s.kuboard.cn/name: smppsim
spec:
  replicas: 1
  selector:
    matchLabels:
      name: smppsim
  template:
    metadata:
      labels:
        name: smppsim
    spec:
      hostname: smppsim
      containers:
      - name: smppsim
        image: jookies/smppsim:latest
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: smppsim
    k8s.kuboard.cn/name: smppsim
  name: smpp-simulator
  namespace: jasmin
spec:
  clusterIP: None
  clusterIPs:
    - None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    name: smppsim
  sessionAffinity: None
  type: ClusterIP
